- hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml
  roles:
    - ./modules

  tasks:
    - name: Create virtual network inteface cards 3
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ network_interface_name }}-3"
        virtual_network: "{{ virtual_network_name }}"
        subnet: "{{ subnet_name }}"

        
    - name: Create VM 3
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ source_vm_name }}-3"
        admin_username: testuser
        admin_password: "Password1234!"
        vm_size: Standard_B1ms
        network_interfaces: "{{ network_interface_name }}-3"
        managed_disk_type: Standard_LRS
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
        data_disks:
          - lun: 0
            disk_size_gb: 4
            managed_disk_type: Standard_LRS